### ISSUE TITLE
Synchronize GitHub tags with composer.json keywords

### ISSUE THREAD

**Issue by webimpress** [zendframework/maintainers#35]
What do you think about adding tool to synchronize `composer.json` **keywords** with GitHub repo **tags**?

**Comment by froschdesign** [comment]
@webimpress 
Great idea! 👍 
At the moment only the owners (@weierophinney and @ezimuel) can edit these tags. If we can write the keywords from the `composer.json` to the repository tags, then we can reduce the work for the repository owners.

Positive side effects:

* consistency between `composer.json` keywords and repository tags
* we can also update the repository tags 😉

**Comment by webimpress** [comment]
@froschdesign not mine idea, @Xerkus suggest it to me on Slack :+1: 
I'm working on the tool :smile:

**Comment by froschdesign** [comment]
@Xerkus 
Great idea! 👍 

@webimpress 
> I'm working on the tool

👍
